---
version: 2
jobs:
  test-cli:
    docker:
      - image: dickeyxxx/heroku-cli:latest
    working_directory: /cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-master
      - run: |
          heroku plugins:link
          heroku plugins:generate example-plugin
          heroku plugins:link example-plugin
          heroku hello:world --name foo
      - save_cache:
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
            - /root/.cache/heroku/yarn

workflows:
  version: 2
  test:
    jobs:
      - test-cli
