#!/bin/bash

set -ex
rm -rf heroku-cli-hello-world/ || true
heroku plugins:generate heroku-cli-hello-world
cd heroku-cli-hello-world
git remote add origin git@github.com:heroku/heroku-cli-hello-world
git push origin master -f
