#!/bin/bash

# use this for testing circle and appveyor

set -ex
rm -rf heroku-cli-hello-world/ || true
heroku plugins:generate heroku-cli-hello-world
cd heroku-cli-hello-world
heroku plugins:unlink heroku-cli-hello-world || true
heroku plugins:link
git remote add origin git@github.com:heroku/heroku-cli-hello-world
git push origin master -f
