#!/usr/bin/env bash

set -ex

rm -rf my-example-plugin

# test ts
heroku plugins:link . -f
heroku plugins:generate my-example-plugin
heroku plugins:link my-example-plugin -f
heroku my-example-plugin:my-example-plugin
heroku help my-example-plugin

rm -rf my-example-plugin

# test js
heroku plugins:link -f .
heroku plugins:generate --type js my-example-plugin
heroku plugins:link -f my-example-plugin
heroku my-example-plugin:my-example-plugin
heroku help my-example-plugin

rm -rf my-example-plugin
